server:
  port: 8001
spring:
  application:
    name: gateway
eureka:
  client:
    service-url:
#      defaultZone: http://root:root@localhost:8000/eureka/
      defaultZone: http://192.168.1.104:30761//eureka/
  instance:
    prefer-ip-address: true
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS