spring:
  application:
    name: MOrchestrationServer
  datasource:
    name: service_evolution
    url: jdbc:mysql://54.65.128.130:3306/service_evolution?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: "root"
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.septemberhx.server.dao

server:
  port: 58080
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://54.65.128.130:8000/eureka


feign:
  hystrix:
    enabled: true