spring:
  application:
    name: MOrchestrationServer
  datasource:
    name: service_evolution
    url: jdbc:mysql://10.11.1.102:3306/service_evolution
    username: root
    password: ices504
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.septemberhx.server.dao

server:
  port: 8082
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${MCLUSTER_IP}:${MCLUSTER_PORT}/eureka

feign:
  client:
    config:
      default:
        connectTimeout: 80000000
        readTimeout: 80000000

msystemevolution:
  orchestration:
    buildCenter:
      ip: ${BUILDCENTER_IP}
      port: ${BUILDCENTER_PORT}
