server:
  port: 8081
spring:
  application:
    name: MServiceAnalyser
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://54.65.128.130:8000/eureka

feign:
  hystrix:
    enabled: true