server:
  port: 8080
spring:
  application:
    name: MServiceAnalyser
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${MCLUSTER_IP}:${MCLUSTER_PORT}/eureka

feign:
  client:
    config:
      default:
        connectTimeout: 80000000
        readTimeout: 80000000