server:
  port: 46832
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://10.111.1.102:30761/eureka

mvf4ms:
  center:
    ip: 10.111.1.102
    port: 2222
  cluster:
    name: test

spring:
  application:
    name: MClusterAgent
mclientagent:
  server:
    ip: 192.168.1.102
    port: 9001
  elasticsearch:
    ip: 192.168.1.102
    port: 4000
  cluster: cluster-01
