server:
  port: 8080

eureka:
  client:
    register-with-eureka: false
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8080/eureka

spring:
  application:
    name: eureka-server-service