package com.septemberhx.server.job;

import com.septemberhx.common.bean.agent.MDeployPodRequest;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

import java.util.UUID;

@Getter
@Setter
@ToString
public class MDeployJob extends MBaseJob {
    private String nodeId;
    private String imageName;
    private String serviceName;
    private String uniqueId;  // to mark the pod with the instance id that generated by the planner

    public MDeployJob(String nodeId, String serviceName, String uniqueId, String imageName) {
        super(MJobType.JOB_DEPLOY);
        this.nodeId = nodeId;
        this.serviceName = serviceName;
        this.uniqueId = uniqueId;
        this.imageName = imageName;
    }

    public MDeployPodRequest toMDeployPodRequest() {
        return new MDeployPodRequest(id, nodeId, uniqueId, serviceName, imageName);
    }
}
